# Generated by Django 6.0.5 on 2026-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='intitulé')),
                ('choice_0', models.CharField(max_length=500)),
                ('choice_1', models.CharField(max_length=500)),
                ('choice_2', models.CharField(max_length=500)),
                ('choice_3', models.CharField(max_length=500)),
                ('correct_index', models.PositiveSmallIntegerField(help_text='Entier entre 0 et 3 (inclus).', verbose_name='index de la bonne réponse')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('correct_index__gte', 0), ('correct_index__lte', 3)), name='question_correct_index_between_0_and_3')],
            },
        ),
    ]
