# Generated by Django 6.0.5 on 2026-05-14 08:26

from django.db import migrations, models
from django.db.models import F, Q


def fill_null_duo_distractor(apps, schema_editor):
    Question = apps.get_model('myapp', 'Question')
    for question in Question.objects.filter(duo_distractor_index__isnull=True):
        for i in (0, 1, 2, 3):
            if i != question.correct_index:
                question.duo_distractor_index = i
                question.save(update_fields=['duo_distractor_index'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='duo_distractor_index',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                help_text=(
                    'En mode duo, l’interface n’affiche que deux propositions : la bonne '
                    '(ci-dessus) et celle-ci. Entier entre 0 et 3, distinct de la bonne réponse.'
                ),
                verbose_name='index de la fausse réponse (mode duo)',
            ),
        ),
        migrations.RunPython(fill_null_duo_distractor, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='duo_distractor_index',
            field=models.PositiveSmallIntegerField(
                help_text=(
                    'En mode duo, l’interface n’affiche que deux propositions : la bonne '
                    '(ci-dessus) et celle-ci. Entier entre 0 et 3, distinct de la bonne réponse.'
                ),
                verbose_name='index de la fausse réponse (mode duo)',
            ),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(
                condition=Q(duo_distractor_index__gte=0)
                & Q(duo_distractor_index__lte=3),
                name='question_duo_distractor_between_0_and_3',
            ),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(
                condition=Q(duo_distractor_index__lt=F('correct_index'))
                | Q(duo_distractor_index__gt=F('correct_index')),
                name='question_duo_distractor_not_correct',
            ),
        ),
    ]
