# Generated by Django 6.0.5 on 2026-05-14 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_question_duo_distractor_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="nom de l'équipe")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparation', 'Préparation'), ('in_progress', 'En cours'), ('finished', 'Terminée')], default='preparation', max_length=20, verbose_name='état')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarrée le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='myapp.team', verbose_name='équipe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre dans l'équipe")),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='myapp.participant', verbose_name='participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='myapp.team', verbose_name='équipe')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='teams', through='myapp.TeamMember', to='myapp.participant', verbose_name='participants'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'participant'), name='team_member_team_participant_uniq'),
        ),
    ]
