# Generated by Django 6.0.5 on 2026-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team_participant_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='correct_answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='bonnes réponses'),
        ),
        migrations.AddField(
            model_name='game',
            name='wrong_answers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='mauvaises réponses'),
        ),
    ]
