# Generated by Django 6.0.5 on 2026-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_game_answer_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='correct_by_carre_count',
            field=models.PositiveIntegerField(default=0, verbose_name='bonnes réponses (mode carré)'),
        ),
        migrations.AddField(
            model_name='game',
            name='correct_by_cash_count',
            field=models.PositiveIntegerField(default=0, verbose_name='bonnes réponses (mode cash)'),
        ),
        migrations.AddField(
            model_name='game',
            name='correct_by_duo_count',
            field=models.PositiveIntegerField(default=0, verbose_name='bonnes réponses (mode duo)'),
        ),
    ]
