# Generated by Django 6.0.5 on 2026-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_game_two_teams_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Image de profil (facultatif pour les fiches déjà créées).', null=True, upload_to='participants/', verbose_name='photo'),
        ),
    ]
