# Generated by Django 6.0.5 on 2026-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_game_play_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='drink_gorgees_team_a',
            field=models.PositiveIntegerField(default=0, verbose_name='gorgées équipe A (erreurs)'),
        ),
        migrations.AddField(
            model_name='game',
            name='drink_gorgees_team_b',
            field=models.PositiveIntegerField(default=0, verbose_name='gorgées équipe B (erreurs)'),
        ),
        migrations.AddField(
            model_name='game',
            name='drink_gorgees_thomas',
            field=models.PositiveIntegerField(default=0, verbose_name='gorgées Thomas (bonnes réponses duo/carré)'),
        ),
        migrations.AddField(
            model_name='game',
            name='drink_shots_team_a',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='shots équipe A (erreur au cash)'),
        ),
        migrations.AddField(
            model_name='game',
            name='drink_shots_team_b',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='shots équipe B (erreur au cash)'),
        ),
        migrations.AddField(
            model_name='game',
            name='drink_shots_thomas',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='shots Thomas (bonne réponse cash)'),
        ),
    ]
